controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

change_locale:
    path: /{_locale}
    controller: App\Controller\LocaleController::index
    requirements:
        _locale: en|fr